CREATE TABLE tMessure ( 
ID_Messure INT NOT NULL ENABLE, 
name NVARCHAR2(250) NOT NULL ENABLE, 
CONSTRAINT pk_messure PRIMARY KEY(ID_messure) ENABLE);

CREATE TABLE tMaterial ( 
ID_Material INT NOT NULL ENABLE, 
name NVARCHAR2(250) NOT NULL ENABLE, 
ID_Messure INT NOT NULL ENABLE, 
CONSTRAINT pk_Material PRIMARY KEY(ID_Material) ENABLE, 
CONSTRAINT fk_Material_Messure FOREIGN KEY (ID_MESSURE) REFERENCES tMessure (ID_Messure) ENABLE);

CREATE TABLE tInprice ( 
ID_Material INT NOT NULL ENABLE, 
price_date DATE NOT NULL ENABLE, 
price NUMBER (10,2) CHECK (price>=0) ENABLE, 
CONSTRAINT fk_Inprice_Material FOREIGN KEY (ID_MATERIAL) REFERENCES TMATERIAL (ID_MATERIAL) ENABLE);

CREATE TABLE tEmployer ( 
ID_Employer INT NOT NULL ENABLE, 
surname NVARCHAR2(250) NOT NULL ENABLE, 
name NVARCHAR2(250) NOT NULL ENABLE, 
father_name NVARCHAR2(250) NOT NULL ENABLE, 
CONSTRAINT pk_employer PRIMARY KEY (ID_EMPLOYER) ENABLE);

CREATE TABLE tSection ( 
ID_Section INT NOT NULL ENABLE, 
name NVARCHAR2(250) NOT NULL ENABLE, 
ID_Employer INT NOT NULL ENABLE, 
CONSTRAINT pk_section PRIMARY KEY (ID_SECTION) ENABLE, 
CONSTRAINT fk_section_employer FOREIGN KEY (ID_EMPLOYER) REFERENCES TEMPLOYER (ID_EMPLOYER) ENABLE);

CREATE TABLE tStore ( 
ID_Store INT NOT NULL ENABLE, 
name NVARCHAR2(250) NOT NULL ENABLE, 
CONSTRAINT pk_store PRIMARY KEY (ID_STORE) ENABLE);

CREATE TABLE tDeliver ( 
ID_Deliver INT NOT NULL ENABLE, 
ID_Section INT NOT NULL ENABLE, 
ID_Material INT NOT NULL ENABLE, 
ID_Store INT NOT NULL ENABLE, 
deliver_date DATE NOT NULL ENABLE, 
CONSTRAINT fk_deliver_section FOREIGN KEY (ID_SECTION) REFERENCES TSECTION (ID_SECTION) ENABLE, 
CONSTRAINT fk_deliver_material FOREIGN KEY (ID_MATERIAL) REFERENCES TMATERIAL (ID_MATERIAL) ENABLE, 
CONSTRAINT fk_deliver_store FOREIGN KEY (ID_STORE) REFERENCES TSTORE (ID_STORE) ENABLE);

CREATE TABLE tSurplus (
ID_Material INT NOT NULL ENABLE,
ID_Store INT NOT NULL ENABLE,
volume NUMBER(10) CHECK (volume>=0) ENABLE,
CONSTRAINT fk_surplus_material FOREIGN KEY (ID_MATERIAL) REFERENCES TMATERIAL (ID_MATERIAL) ENABLE, 
CONSTRAINT fk_surplus_store FOREIGN KEY (ID_STORE) REFERENCES TSTORE (ID_STORE) ENABLE); 

CREATE TABLE tCaterer ( 
ID_Caterer INT NOT NULL ENABLE, 
name NVARCHAR2(250) NOT NULL ENABLE, 
address NVARCHAR2(250) NOT NULL ENABLE, 
phone NVARCHAR2(12) NOT NULL ENABLE, 
fax NVARCHAR2(12) NOT NULL ENABLE, 
CONSTRAINT pk_caterer PRIMARY KEY(ID_CATERER) ENABLE);

CREATE TABLE tSupply ( 
ID_Supply INT NOT NULL ENABLE,
ID_Caterer INT NOT NULL ENABLE,
ID_Material INT NOT NULL ENABLE,
ID_Store INT NOT NULL ENABLE,
supply_date DATE NOT NULL ENABLE, 
volume NUMBER(10) CHECK (volume>=0) ENABLE,
CONSTRAINT fk_supply_caterer FOREIGN KEY (ID_CATERER) REFERENCES TCATERER (ID_CATERER) ENABLE,
CONSTRAINT fk_supply_material FOREIGN KEY (ID_MATERIAL) REFERENCES TMATERIAL (ID_MATERIAL) ENABLE,
CONSTRAINT fk_supply_store FOREIGN KEY (ID_STORE) REFERENCES TSTORE (ID_STORE) ENABLE);
